version: "2"

services: 
  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ginSample
      - MYSQL_ROOT_PASSWORD=root